version: '3'
services:

  db:
    container_name: mysqldb
    image: mysql:latest
    healthcheck:
      test: "exit 0"
    volumes:
      - ../dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: projectmanagerdb

  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mypassword
      DB_NAME: projectmanagerdb
    links:
      - db
    depends_on:
      - db

volumes:
  db_data:
